version: "2"
exclude_patterns:
  - "spec/"
  - "lib/graphql8/language/lexer.rb"
  - "lib/graphql8/language/parser.rb"
  # plugin - duplication - is failing on these
  - "spec/graphql8/language/printer_spec.rb"
  - "lib/graphql8/compatibility/query_parser_specification.rb"
